FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.26-openshift-5.0 AS builder
WORKDIR /go/src/github.com/openshift/kueue-operator
COPY . .

RUN make build

FROM registry.ci.openshift.org/ocp/builder:rhel-9-enterprise-base-multi-openshift-4.19
COPY --from=builder /go/src/github.com/openshift/kueue-operator/kueue-operator /usr/bin/
COPY --from=builder /go/src/github.com/openshift/kueue-operator/manifests/* /manifests/
COPY --from=builder /usr/bin/lsof /usr/bin/lsof

LABEL io.k8s.display-name="OpenShift Kueue Operator based on RHEL 9" \
      io.k8s.description="This is a component of OpenShift and manages kueue based on RHEL 9" \
      io.openshift.tags="openshift,kueue-operator" \
      com.redhat.delivery.appregistry=true \
      maintainer="AOS Node team, <aos-node@redhat.com>"

USER 1001
